version: '3.8'
services:
 server1:
  build:
   context: ./server1
  ports:
   - '8000:8000'
  container_name: server1
  depends_on:
   - nginx

 server2:
  build:
   context: ./server2
  ports:
   - '8001:8001'
  container_name: server2
  depends_on:
   - nginx

 nginx:
  restart: always
  image: nginx:latest
  container_name: nginx
  volumes:
   - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
  ports:
   - '8080:80'
